newsh

diff --git a/bin/newsh b/bin/newsh
--- a/bin/newsh
+++ b/bin/newsh
@@ -15,17 +15,301 @@ else
     this="$(cd $(dirname $rpath) && pwd)"
 fi
 
-if [ -r ${SHELLRC_ROOT}/shelllib ]; then
-    source ${SHELLRC_ROOT}/shelllib
-elif [ -r /tmp/shelllib ]; then
-    source /tmp/shelllib
+export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+
+user="${SUDO_USER:-$(whoami)}"
+home="$(eval echo ~$user)"
+
+# export TERM=xterm-256color
+
+# Use colors, but only if connected to a terminal, and that terminal
+# supports them.
+if which tput >/dev/null 2>&1; then
+    ncolors=$(tput colors 2>/dev/null)
+fi
+if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
+    RED="$(tput setaf 1)"
+    GREEN="$(tput setaf 2)"
+    YELLOW="$(tput setaf 3)"
+    BLUE="$(tput setaf 4)"
+    CYAN="$(tput setaf 5)"
+    BOLD="$(tput bold)"
+    NORMAL="$(tput sgr0)"
 else
-    # download shelllib then source
-    shelllibURL=https://gitee.com/sunliang711/init2/raw/master/shell/shellrc.d/shelllib
-    (cd /tmp && curl -s -LO ${shelllibURL})
-    if [ -r /tmp/shelllib ]; then
-        source /tmp/shelllib
+    RED=""
+    GREEN=""
+    YELLOW=""
+    CYAN=""
+    BLUE=""
+    BOLD=""
+    NORMAL=""
+fi
+
+# error code
+err_require_root=1
+err_require_linux=2
+err_require_command=3
+
+_err() {
+    echo "$*" >&2
+}
+
+_command_exists() {
+    command -v "$1" >/dev/null 2>&1
+}
+
+_require_command() {
+    if ! _command_exists "$1"; then
+        echo "require command $1" 1>&2
+        exit ${err_require_command}
     fi
+}
+
+rootID=0
+
+_runAsRoot() {
+    local trace=0
+    local subshell=0
+    local nostdout=0
+    local nostderr=0
+
+    local optNum=0
+    for opt in ${@}; do
+        case "${opt}" in
+        --trace | -x)
+            trace=1
+            ((optNum++))
+            ;;
+        --subshell | -s)
+            subshell=1
+            ((optNum++))
+            ;;
+        --no-stdout)
+            nostdout=1
+            ((optNum++))
+            ;;
+        --no-stderr)
+            nostderr=1
+            ((optNum++))
+            ;;
+        *)
+            break
+            ;;
+        esac
+    done
+
+    shift $(($optNum))
+    local cmd="${*}"
+    bash_c='bash -c'
+    if [ "${EUID}" -ne "${rootID}" ]; then
+        if _command_exists sudo; then
+            bash_c='sudo -E bash -c'
+        elif _command_exists su; then
+            bash_c='su -c'
+        else
+            cat >&2 <<-'EOF'
+			Error: this installer needs the ability to run commands as root.
+			We are unable to find either "sudo" or "su" available to make this happen.
+			EOF
+            return 1
+        fi
+    fi
+
+    local fullcommand="${bash_c} ${cmd}"
+    if [ $nostdout -eq 1 ]; then
+        cmd="${cmd} >/dev/null"
+    fi
+    if [ $nostderr -eq 1 ]; then
+        cmd="${cmd} 2>/dev/null"
+    fi
+
+    if [ $subshell -eq 1 ]; then
+        if [ $trace -eq 1 ]; then
+            (
+                { set -x; } 2>/dev/null
+                ${bash_c} "${cmd}"
+            )
+        else
+            (${bash_c} "${cmd}")
+        fi
+    else
+        if [ $trace -eq 1 ]; then
+            { set -x; } 2>/dev/null
+            ${bash_c} "${cmd}"
+            local ret=$?
+            { set +x; } 2>/dev/null
+            return $ret
+        else
+            ${bash_c} "${cmd}"
+        fi
+    fi
+}
+
+function _insert_path() {
+    if [ -z "$1" ]; then
+        return
+    fi
+    echo -e ${PATH//:/"\n"} | grep -c "^$1$" >/dev/null 2>&1 || export PATH=$1:$PATH
+}
+
+_run() {
+    local trace=0
+    local subshell=0
+    local nostdout=0
+    local nostderr=0
+
+    local optNum=0
+    for opt in ${@}; do
+        case "${opt}" in
+        --trace | -x)
+            trace=1
+            ((optNum++))
+            ;;
+        --subshell | -s)
+            subshell=1
+            ((optNum++))
+            ;;
+        --no-stdout)
+            nostdout=1
+            ((optNum++))
+            ;;
+        --no-stderr)
+            nostderr=1
+            ((optNum++))
+            ;;
+        *)
+            break
+            ;;
+        esac
+    done
+
+    shift $(($optNum))
+    local cmd="${*}"
+    bash_c='bash -c'
+
+    local fullcommand="${bash_c} ${cmd}"
+    if [ $nostdout -eq 1 ]; then
+        cmd="${cmd} >/dev/null"
+    fi
+    if [ $nostderr -eq 1 ]; then
+        cmd="${cmd} 2>/dev/null"
+    fi
+
+    if [ $subshell -eq 1 ]; then
+        if [ $trace -eq 1 ]; then
+            (
+                { set -x; } 2>/dev/null
+                ${bash_c} "${cmd}"
+            )
+        else
+            (${bash_c} "${cmd}")
+        fi
+    else
+        if [ $trace -eq 1 ]; then
+            { set -x; } 2>/dev/null
+            ${bash_c} "${cmd}"
+            { local ret=$?; } 2>/dev/null
+            { set +x; } 2>/dev/null
+            return ${ret}
+        else
+            ${bash_c} "${cmd}"
+        fi
+    fi
+}
+
+function _ensureDir() {
+    local dirs=$@
+    for dir in ${dirs}; do
+        if [ ! -d ${dir} ]; then
+            mkdir -p ${dir} || {
+                echo "create $dir failed!"
+                exit 1
+            }
+        fi
+    done
+}
+
+function _root() {
+    if [ ${EUID} -ne ${rootID} ]; then
+        echo "Require root privilege." 1>&2
+        return $err_require_root
+    fi
+}
+
+function _require_root() {
+    if ! _root; then
+        exit $err_require_root
+    fi
+}
+
+function _linux() {
+    if [ "$(uname)" != "Linux" ]; then
+        echo "Require Linux" 1>&2
+        return $err_require_linux
+    fi
+}
+
+function _require_linux() {
+    if ! _linux; then
+        exit $err_require_linux
+    fi
+}
+
+function _wait() {
+    # secs=$((5 * 60))
+    secs=${1:?'missing seconds'}
+
+    while [ $secs -gt 0 ]; do
+        echo -ne "$secs\033[0K\r"
+        sleep 1
+        : $((secs--))
+    done
+    echo -ne "\033[0K\r"
+}
+
+_must_ok() {
+    if [ $? != 0 ]; then
+        echo "failed,exit.."
+        exit $?
+    fi
+}
+
+_info() {
+    echo -n "$(date +%FT%T) ${1}"
+}
+
+_infoln() {
+    echo "$(date +%FT%T) ${1}"
+}
+
+_error() {
+    echo -n "$(date +%FT%T) ${RED}${1}${NORMAL}"
+}
+
+_errorln() {
+    echo "$(date +%FT%T) ${RED}${1}${NORMAL}"
+}
+
+_checkService() {
+    _info "find service ${1}.."
+    if systemctl --all --no-pager | grep -q "${1}"; then
+        echo "OK"
+    else
+        echo "Not found"
+        return 1
+    fi
+}
+
+ed=vi
+if _command_exists vim; then
+    ed=vim
+fi
+if _command_exists nvim; then
+    ed=nvim
+fi
+# use ENV: editor to override
+if [ -n "${editor}" ]; then
+    ed=${editor}
 fi
 
 # available VARs: user, home, rootID
