shTmpl

diff --git a/bin/shTmpl b/bin/shTmpl
--- a/bin/shTmpl
+++ b/bin/shTmpl
@@ -196,84 +196,97 @@ fi
 
 rootID=0
 
-# 用法: _runAsRoot [-x] [-s] [--no-stdout] [--no-stderr] <command>
-_runAsRoot() {
-    local trace=0
-    local subshell=0
-    local nostdout=0
-    local nostderr=0
-
-    local optNum=0
-    for opt in ${@}; do
-        case "${opt}" in
-        --trace | -x)
-            trace=1
-            ((optNum++))
-            ;;
-        --subshell | -s)
-            subshell=1
-            ((optNum++))
-            ;;
-        --no-stdout)
-            nostdout=1
-            ((optNum++))
-            ;;
-        --no-stderr)
-            nostderr=1
-            ((optNum++))
-            ;;
-        *)
-            break
-            ;;
-        esac
-    done
-
-    shift $(($optNum))
-    local cmd="${*}"
-    bash_c='bash -c'
-    if [ "${EUID}" -ne "${rootID}" ]; then
-        if _command_exists sudo; then
-            bash_c='sudo -E bash -c'
-        elif _command_exists su; then
-            bash_c='su -c'
-        else
-            cat >&2 <<-'EOF'
-			Error: this installer needs the ability to run commands as root.
-			We are unable to find either "sudo" or "su" available to make this happen.
-			EOF
+runAsRoot() {
+    if [ "$(id -u)" -eq 0 ]; then
+        echo "Running as root: $*"
+        "$@"
+    else
+        if ! command -v sudo >/dev/null 2>&1; then
+            echo "Error: 'sudo' is required but not found." >&2
             return 1
         fi
-    fi
-
-    local fullcommand="${bash_c} ${cmd}"
-    if [ $nostdout -eq 1 ]; then
-        cmd="${cmd} >/dev/null"
-    fi
-    if [ $nostderr -eq 1 ]; then
-        cmd="${cmd} 2>/dev/null"
-    fi
-
-    if [ $subshell -eq 1 ]; then
-        if [ $trace -eq 1 ]; then
-            (
-                { set -x; } 2>/dev/null
-                ${bash_c} "${cmd}"
-            )
-        else
-            (${bash_c} "${cmd}")
-        fi
-    else
-        if [ $trace -eq 1 ]; then
-            { set -x; } 2>/dev/null
-            ${bash_c} "${cmd}"
-            local ret=$?
-            { set +x; } 2>/dev/null
-            return $ret
-        else
-            ${bash_c} "${cmd}"
-        fi
+        echo "Using sudo: $*"
+        sudo "$@"
     fi
 }
+# # 用法: _runAsRoot [-x] [-s] [--no-stdout] [--no-stderr] <command>
+# _runAsRoot() {
+#     local trace=0
+#     local subshell=0
+#     local nostdout=0
+#     local nostderr=0
+
+#     local optNum=0
+#     for opt in ${@}; do
+#         case "${opt}" in
+#         --trace | -x)
+#             trace=1
+#             ((optNum++))
+#             ;;
+#         --subshell | -s)
+#             subshell=1
+#             ((optNum++))
+#             ;;
+#         --no-stdout)
+#             nostdout=1
+#             ((optNum++))
+#             ;;
+#         --no-stderr)
+#             nostderr=1
+#             ((optNum++))
+#             ;;
+#         *)
+#             break
+#             ;;
+#         esac
+#     done
+
+#     shift $(($optNum))
+#     local cmd="${*}"
+#     bash_c='bash -c'
+#     if [ "${EUID}" -ne "${rootID}" ]; then
+#         if _command_exists sudo; then
+#             bash_c='sudo -E bash -c'
+#         elif _command_exists su; then
+#             bash_c='su -c'
+#         else
+#             cat >&2 <<-'EOF'
+# 			Error: this installer needs the ability to run commands as root.
+# 			We are unable to find either "sudo" or "su" available to make this happen.
+# 			EOF
+#             return 1
+#         fi
+#     fi
+
+#     local fullcommand="${bash_c} ${cmd}"
+#     if [ $nostdout -eq 1 ]; then
+#         cmd="${cmd} >/dev/null"
+#     fi
+#     if [ $nostderr -eq 1 ]; then
+#         cmd="${cmd} 2>/dev/null"
+#     fi
+
+#     if [ $subshell -eq 1 ]; then
+#         if [ $trace -eq 1 ]; then
+#             (
+#                 { set -x; } 2>/dev/null
+#                 ${bash_c} "${cmd}"
+#             )
+#         else
+#             (${bash_c} "${cmd}")
+#         fi
+#     else
+#         if [ $trace -eq 1 ]; then
+#             { set -x; } 2>/dev/null
+#             ${bash_c} "${cmd}"
+#             local ret=$?
+#             { set +x; } 2>/dev/null
+#             return $ret
+#         else
+#             ${bash_c} "${cmd}"
+#         fi
+#     fi
+# }
 
 # 日志级别名称数组及最大长度计算
 LOG_LEVELS=("FATAL" "ERROR" "WARNING" "INFO" "SUCCESS" "DEBUG")
