newsh

diff --git a/shellConfigs/shelllib b/shellConfigs/shelllib
--- a/shellConfigs/shelllib
+++ b/shellConfigs/shelllib
@@ -1,4 +1,3 @@
-
 export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 
 user="${SUDO_USER:-$(whoami)}"
@@ -9,7 +8,7 @@ home="$(eval echo ~$user)"
 # Use colors, but only if connected to a terminal, and that terminal
 # supports them.
 if which tput >/dev/null 2>&1; then
-  ncolors=$(tput colors 2>/dev/null)
+    ncolors=$(tput colors 2>/dev/null)
 fi
 if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
     RED="$(tput setaf 1)"
@@ -34,59 +33,58 @@ err_require_root=1
 err_require_linux=2
 err_require_command=3
 
-
-_err(){
+_err() {
     echo "$*" >&2
 }
 
-_command_exists(){
-    command -v "$1" > /dev/null 2>&1
+_command_exists() {
+    command -v "$1" >/dev/null 2>&1
 }
 
-_require_command(){
-    if ! _command_exists "$1";then
+_require_command() {
+    if ! _command_exists "$1"; then
         echo "require command $1" 1>&2
-	    exit ${err_require_command}
+        exit ${err_require_command}
     fi
 }
 
 rootID=0
 
-_runAsRoot(){
+_runAsRoot() {
     local trace=0
     local subshell=0
     local nostdout=0
     local nostderr=0
 
     local optNum=0
-    for opt in ${@};do
+    for opt in ${@}; do
         case "${opt}" in
-            --trace|-x)
-                trace=1
-                ((optNum++))
-                ;;
-            --subshell|-s)
-                subshell=1
-                ((optNum++))
-                ;;
-            --no-stdout)
-                nostdout=1
-                ((optNum++))
-                ;;
-            --no-stderr)
-                nostderr=1
-                ((optNum++))
-                ;;
-            *)
-                break
-                ;;
+        --trace | -x)
+            trace=1
+            ((optNum++))
+            ;;
+        --subshell | -s)
+            subshell=1
+            ((optNum++))
+            ;;
+        --no-stdout)
+            nostdout=1
+            ((optNum++))
+            ;;
+        --no-stderr)
+            nostderr=1
+            ((optNum++))
+            ;;
+        *)
+            break
+            ;;
         esac
     done
 
     shift $(($optNum))
     local cmd="${*}"
     bash_c='bash -c'
-    if [ "${EUID}" -ne "${rootID}" ];then
+    if [ "${EUID}" -ne "${rootID}" ]; then
         if _command_exists sudo; then
             bash_c='sudo -E bash -c'
         elif _command_exists su; then
@@ -101,24 +99,24 @@ _runAsRoot(){
     fi
 
     local fullcommand="${bash_c} ${cmd}"
-    if [ $nostdout -eq 1 ];then
+    if [ $nostdout -eq 1 ]; then
         cmd="${cmd} >/dev/null"
     fi
-    if [ $nostderr -eq 1 ];then
+    if [ $nostderr -eq 1 ]; then
         cmd="${cmd} 2>/dev/null"
     fi
 
-    if [ $subshell -eq 1 ];then
-        if [ $trace -eq 1 ];then
+    if [ $subshell -eq 1 ]; then
+        if [ $trace -eq 1 ]; then
             (
-             { set -x;} 2>/dev/null
-             ${bash_c} "${cmd}"
+                { set -x; } 2>/dev/null
+                ${bash_c} "${cmd}"
             )
         else
             (${bash_c} "${cmd}")
         fi
     else
-        if [ $trace -eq 1 ];then
+        if [ $trace -eq 1 ]; then
             { set -x; } 2>/dev/null
             ${bash_c} "${cmd}"
             local ret=$?
@@ -130,41 +128,41 @@ _runAsRoot(){
     fi
 }
 
-function _insert_path(){
-    if [ -z "$1" ];then
+function _insert_path() {
+    if [ -z "$1" ]; then
         return
     fi
     echo -e ${PATH//:/"\n"} | grep -c "^$1$" >/dev/null 2>&1 || export PATH=$1:$PATH
 }
 
-_run(){
+_run() {
     local trace=0
     local subshell=0
     local nostdout=0
     local nostderr=0
 
     local optNum=0
-    for opt in ${@};do
+    for opt in ${@}; do
         case "${opt}" in
-            --trace|-x)
-                trace=1
-                ((optNum++))
-                ;;
-            --subshell|-s)
-                subshell=1
-                ((optNum++))
-                ;;
-            --no-stdout)
-                nostdout=1
-                ((optNum++))
-                ;;
-            --no-stderr)
-                nostderr=1
-                ((optNum++))
-                ;;
-            *)
-                break
-                ;;
+        --trace | -x)
+            trace=1
+            ((optNum++))
+            ;;
+        --subshell | -s)
+            subshell=1
+            ((optNum++))
+            ;;
+        --no-stdout)
+            nostdout=1
+            ((optNum++))
+            ;;
+        --no-stderr)
+            nostderr=1
+            ((optNum++))
+            ;;
+        *)
+            break
+            ;;
         esac
     done
 
@@ -173,15 +171,15 @@ _run(){
     bash_c='bash -c'
 
     local fullcommand="${bash_c} ${cmd}"
-    if [ $nostdout -eq 1 ];then
+    if [ $nostdout -eq 1 ]; then
         cmd="${cmd} >/dev/null"
     fi
-    if [ $nostderr -eq 1 ];then
+    if [ $nostderr -eq 1 ]; then
         cmd="${cmd} 2>/dev/null"
     fi
 
-    if [ $subshell -eq 1 ];then
-        if [ $trace -eq 1 ];then
+    if [ $subshell -eq 1 ]; then
+        if [ $trace -eq 1 ]; then
             (
                 { set -x; } 2>/dev/null
                 ${bash_c} "${cmd}"
@@ -190,7 +188,7 @@ _run(){
             (${bash_c} "${cmd}")
         fi
     else
-        if [ $trace -eq 1 ];then
+        if [ $trace -eq 1 ]; then
             { set -x; } 2>/dev/null
             ${bash_c} "${cmd}"
             { local ret=$?; } 2>/dev/null
@@ -202,79 +200,82 @@ _run(){
     fi
 }
 
-function _ensureDir(){
+function _ensureDir() {
     local dirs=$@
-    for dir in ${dirs};do
-        if [ ! -d ${dir} ];then
-            mkdir -p ${dir}
+    for dir in ${dirs}; do
+        if [ ! -d ${dir} ]; then
+            mkdir -p ${dir} || {
+                echo "create $dir failed!"
+                exit 1
+            }
         fi
     done
 }
 
-function _root(){
-    if [ ${EUID} -ne ${rootID} ];then
+function _root() {
+    if [ ${EUID} -ne ${rootID} ]; then
         echo "Require root privilege." 1>&2
         return $err_require_root
     fi
 }
 
-function _require_root(){
-    if ! _root;then
+function _require_root() {
+    if ! _root; then
         exit $err_require_root
     fi
 }
 
-function _linux(){
-    if [ "$(uname)" != "Linux" ];then
+function _linux() {
+    if [ "$(uname)" != "Linux" ]; then
         echo "Require Linux" 1>&2
         return $err_require_linux
     fi
 }
 
-function _require_linux(){
-    if ! _linux;then
+function _require_linux() {
+    if ! _linux; then
         exit $err_require_linux
     fi
 }
 
-function _wait(){
+function _wait() {
     # secs=$((5 * 60))
     secs=${1:?'missing seconds'}
 
     while [ $secs -gt 0 ]; do
-       echo -ne "$secs\033[0K\r"
-       sleep 1
-       : $((secs--))
+        echo -ne "$secs\033[0K\r"
+        sleep 1
+        : $((secs--))
     done
     echo -ne "\033[0K\r"
 }
 
-_must_ok(){
-    if [ $? != 0 ];then
+_must_ok() {
+    if [ $? != 0 ]; then
         echo "failed,exit.."
         exit $?
     fi
 }
 
-_info(){
+_info() {
     echo -n "$(date +%FT%T) ${1}"
 }
 
-_infoln(){
+_infoln() {
     echo "$(date +%FT%T) ${1}"
 }
 
-_error(){
+_error() {
     echo -n "$(date +%FT%T) ${RED}${1}${NORMAL}"
 }
 
-_errorln(){
+_errorln() {
     echo "$(date +%FT%T) ${RED}${1}${NORMAL}"
 }
 
-_checkService(){
+_checkService() {
     _info "find service ${1}.."
-    if systemctl --all --no-pager | grep -q "${1}";then
+    if systemctl --all --no-pager | grep -q "${1}"; then
         echo "OK"
     else
         echo "Not found"
@@ -290,7 +291,7 @@ if _command_exists nvim; then
     ed=nvim
 fi
 # use ENV: editor to override
-if [ -n "${editor}" ];then
+if [ -n "${editor}" ]; then
     ed=${editor}
 fi
 
@@ -446,9 +447,16 @@ _print_bar_text() {
     fi
 
     # Prepare progress bar
-    let complete_size=($bar_size*$percentage)/100
+    let complete_size=($bar_size * $percentage)/100
     let remainder_size=$bar_size-$complete_size
-    progress_bar=$(echo -ne "["; echo -en "${color}"; _printf_new "#" $complete_size; echo -en "${RESTORE_FG}${RESTORE_BG}"; _printf_new "." $remainder_size; echo -ne "]");
+    progress_bar=$(
+        echo -ne "["
+        echo -en "${color}"
+        _printf_new "#" $complete_size
+        echo -en "${RESTORE_FG}${RESTORE_BG}"
+        _printf_new "." $remainder_size
+        echo -ne "]"
+    )
 
     # Print progress bar
     echo -ne " Progress ${percentage}% ${progress_bar}"
